### ISSUE TITLE
[Q] Appropriate for use in production?

### ISSUE THREAD

**Issue by lonix1** [cpear/BlazorComponentBus#10]
Hello @cpear.

Thank you for making this library. I'm new to blazor wasm and am looking for a way to handle state. There's the way promoted by MS (using cascading values, state container objects, etc.), fluxor and blazor-state.

I've been using fluxor - which is quite incredible - but then realised it's the wrong tool for our smallish app. So I started looking for a simpler tool, and found this!

I've played around with it a bit, and think it's really wonderful - especially for small apps, or large apps which lack complexity as they are basically "CRUDy".

My only concern is that it lacks the traction enjoyed by fluxor. Please don't take that as an insult, I just wish there were a larger community. Early days I guess!

My question: is this a side project, or do you actually use it in production for commercial purposes? Put differently, is it still in beta mode? Does it scale well once your app gets larger? Any tips in this area would be appreciated.

Thanks once more, I'm really enjoying it so far!

**Comment by cpear** [comment]
The short answer is that I have not done any extensive  testing around how well it will hold up under any type of load.

**Comment by lonix1** [comment]
Fair enough. But do you use it in production or for personal projects?

**Comment by cjbush** [comment]
@lonix1 We're currently using it in production for an internal site and haven't seen any problems with load. Small sample size, but do with that information what you will 😄

**Comment by lonix1** [comment]
Thanks cjbush
