### ISSUE TITLE
[Q] Use with a state container

### ISSUE THREAD

**Issue by lonix1** [cpear/BlazorComponentBus#11]
Hi again @cpear!

I initially thought this was a state management tool, but now I realise it's mostly for inter-component messaging. I'm having lots of fun using it, as it simplified my codebase quite a bit.

But I've not yet figured out how to perform state management. My initial thought was to send a message directly to a state container (which subscribes to said message), which updates itself, then raises an event; subscribing components would then detect that change and issue `StateHasChanged()`.

Is that how you do it? Or is there a better way?

**Comment by cpear** [comment]
Hi @lonix1 

The context of your question is important I suppose. By that I mean what are you really trying to achieve? 😀

I guess the thing to remember is that BlazorComponentBus is running in memory. So it's not really durable in terms of any long term memory.

So typically with messaging like this I would try to keep each module independent and have them all persist their own data as opposed to a centralized version of data. 

One of my next little projects is to try to implement Udi Dahan's Service Oriented composition which basically shows how one might aggregate data from each component for making calls to an api.

https://udidahan.com/2014/07/30/service-oriented-composition-with-video/

**Comment by lonix1** [comment]
Thanks for your insights.
