### ISSUE TITLE
[Question] Using BlazorComponentBus outside of Razor Components?

### ISSUE THREAD

**Issue by ryanbuening** [cpear/BlazorComponentBus#12]
Are there any things to watch out for, or downsides when using BlazorComponentBus outside of strictly Razor components?

For example, I was playing around with BlazorComponentBus in my [BlazorBazaar](https://github.com/ryanbuening/blazor-bazaar/tree/main/src/BlazorBazaar.Web) repo and using the Bus in a ShoppingCart service to [publish a message](https://github.com/ryanbuening/blazor-bazaar/blob/1b500162352b25aedbcb914827bca18c1cb4025d/src/BlazorBazaar.Web/Features/Cart/CartService.cs#L53-L53) when the cart was modified. That message [gets picked up by the Header Razor component](https://github.com/ryanbuening/blazor-bazaar/blob/1b500162352b25aedbcb914827bca18c1cb4025d/src/BlazorBazaar.Web/Features/Header.razor#L35-L35) to update the cart count.

**Comment by cpear** [comment]
I don't see anything that sticks out from your described usage.  :-)

**Comment by cpear** [comment]
X
