### ISSUE TITLE
Unsubscribe

### ISSUE THREAD

**Issue by cpear** [cpear/BlazorComponentBus#2]
As an Engineer I need the ability to have a component unsubscribe from the message broker so it will no longer respond to specific messages.

**Comment by jkears** [comment]
I am having a similar need, I notice that I am getting as many events per as many times I invoke a page with a component that subscribes to an event.  We need to be able to unsubscribe in the Dispose method.

**Comment by jkears** [comment]
Is an unsubscribe method as simple as the following...

`public void UnSubscribe<T>(ComponentCallBack<MessageArgs> componentCallBack)
 {
            try
            {
                _registeredComponents.Remove(new KeyValuePair<Type, ComponentCallBack<MessageArgs>>(typeof(T), componentCallBack));
            }
            catch { }
        }`

**Comment by titobf** [comment]
Hi. Is this project abandoned?

**Comment by cpear** [comment]
No. It's not abandoned.

**Comment by cpear** [comment]
v2.0.0 now supports unsubscribe
