### ISSUE TITLE
Maui blazor compatible?

### ISSUE THREAD

**Issue by julianadormon** [cpear/BlazorComponentBus#8]
Hey, thanks for building this.
I tried to implement this  in a MUi Blazor app and while there are no errors publishing a message, the subscribed component never seems to get the message. Perhaps I am doing so.ething wrong but wanted to know if this is even compatible with Maui?

Thanks.

**Comment by cpear** [comment]
Hi. I am not sure if the package will work with Maui and it would be difficult for me to test it as I am not familiar with creating apps in Maui. Do you perhaps have an example branch of code somewhere that reproduces the error you are seeing?
